# Generated by Django 4.1.3 on 2022-11-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField()),
                ('title', models.TextField(max_length=100)),
                ('yt_url', models.URLField(null=True)),
                ('rating', models.IntegerField(default=1400)),
            ],
        ),
    ]
